cat << EOF
FROM golang:1.9.2-alpine3.7 AS build

RUN apk add --no-cache git make
RUN go get github.com/golang/dep/cmd/dep

COPY Gopkg.lock Gopkg.toml /go/src/${NAME}/
WORKDIR /go/src/${NAME}
RUN dep ensure -vendor-only

COPY . /go/src/${NAME}
RUN make static-build

FROM scratch
COPY --from=build /go/src/${NAME}/bin/${NAME} /bin/${NAME}
ENTRYPOINT ["/bin/${NAME}"]
EOF
