cat << __EOF__
FROM golang:1.10.1-alpine3.7 AS build

ENV DEP_VERSION 0.4.1

RUN apk add -q --no-progress --no-cache git make ca-certificates
RUN wget -q -O /usr/local/bin/dep https://github.com/golang/dep/releases/download/v\${DEP_VERSION}/dep-linux-amd64 && chmod +x /usr/local/bin/dep
RUN wget -q -O /usr/local/bin/depinst https://github.com/orisano/depinst/releases/download/1.0.0/depinst-linux-amd64 && chmod +x /usr/local/bin/depinst

WORKDIR /go/src/${DIR}
COPY Gopkg.lock Gopkg.toml ./
RUN dep ensure -vendor-only

COPY . .
RUN make static-build

FROM alpine:3.7
RUN apk add -q --no-progress --no-cache ca-certificates
COPY --from=build /go/src/${DIR}/bin/${NAME} /bin/${NAME}
ENTRYPOINT ["/bin/${NAME}"]
__EOF__
